routes/web.php
<?php

use App\Http\Middleware\IsAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin pages
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::resource('/admin/details', 'PhotoDetailsController')->middleware('is_admin');
Route::resource('/admin/announcements', 'AnnouncementsController')->middleware('is_admin');
Route::resource('/admin/challenges', 'WeeklyChallengeController')->middleware('is_admin');
Route::resource('/admin/gallery', 'GalleryController')->middleware('is_admin');
Route::resource('/admin/blog', 'BlogController')->middleware('is_admin');
Route::resource('/admin/sales', 'SalesController')->middleware('is_admin');
Route::resource('/admin/workshop', 'WorkshopController')->middleware('is_admin');
Route::resource('/admin/courses', 'CoursesController')->middleware('is_admin');


//Route::resource('admin/blog', 'BlogController');

//user pages
Route::get('/home' , [
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::get('/test', function () {
   return view('admin');
});

//site
Route::get('/', function () {
    return redirect()->route('intro');
})->name('index');

Route::get('/intro', function () {
    return view('Front.includes.intro');
})->name('intro');

Route::post('contact-us', [
    'uses'=>'WebController@contactUs',
    'as'=>'contact-us']
);

Route::get('/blog', [
    'uses' => 'WebController@paginateBlog',
    'as' => 'blog'
]);
Route::resource('blogArticle', 'BlogController');

Route::get('/sales', [
    'uses' => 'WebController@paginateSales',
    'as' => 'sales'
]);

Route::get('/workshop', [
    'uses' => 'WebController@paginateWorkshos',
    'as' => 'workshop'
]);

Route::get('/increaseWorkshop', [
    'uses' => 'WebController@increaseWorkshopParticipate',
    'as' => 'increaseWorkshop'
]);

Route::get('/courses', function () {
    return view('Front.includes.courses');
})->name('courses');

Route::get('/gallery', 'WebController@getAllImages')->name('gallery');

Route::get('/weekly', [
    'uses' => 'WebController@getCurentWeeklyChallenge',
    'as' => 'weekly'
]);

Route::get('/increaseLike', [
    'uses' => 'WebController@increaseLike',
    'as' => 'increaseLike'
]);

Route::get('/increaseView', [
    'uses' => 'WebController@increaseView',
    'as' => 'increaseView'
]);

Route::get('/increaseVoteChallenge', [
    'uses' => 'WebController@increaseVoteChallenge',
    'as' => 'increaseVoteChallenge'
]);

Route::post('/uploadWeekly', [
    'uses' => 'WebController@uploadWeekly',
    'as' => 'uploadWeekly'
]);

Route::get('/blog/searchBlog/{variable}',[
   'uses' => 'WebController@searchBlog',
   'as' => 'searchBlog'
]);



//admin-panel
Route::get('/admin/camera/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit1',
    'as' => 'details.edit1'
]);
Route::put('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@update1',
    'as' => 'details.update1'
]);
Route::delete('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@destroy1',
    'as' => 'details.destroy1'
]);


Route::get('/admin/exposure/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit2',
    'as' => 'details.edit2'
]);
Route::put('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@update2',
    'as' => 'details.update2'
]);
Route::delete('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@destroy2',
    'as' => 'details.destroy2'
]);

Route::get('/admin/lens/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit3',
    'as' => 'details.edit3'
]);
Route::put('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@update3',
    'as' => 'details.update3'
]);
Route::delete('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@destroy3',
    'as' => 'details.destroy3'
]);

Route::get('/admin/diaphragm/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit4',
    'as' => 'details.edit4'
]);
Route::put('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@update4',
    'as' => 'details.update4'
]);
Route::delete('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@destroy4',
    'as' => 'details.destroy4'
]);

Route::delete('/admin/photos/{details}', [
    'uses' => 'WeeklyChallengeController@destroyPhoto',
    'as' => 'weekly.destroyPhoto'
]);


Auth::routes();

resources/views/back_admin/technical_details/create.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Adauga detalii tehnice</h1>

        <div class="row justify-content-center">
            {!! Form::open(['method' => 'POST', 'action' => 'PhotoDetailsController@store']) !!}

            <div class="form-group">
                {!! Form::label('iso', 'ISO:') !!}
                {!! Form::text('iso', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('camera', 'Camera') !!}
                {!! Form::text('camera', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('exposure', 'Expunere:') !!}
                {!! Form::text('exposure', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('lens', 'Obiectiv:') !!}
                {!! Form::text('lens', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('diaphragm', 'Diafragma:') !!}
                {!! Form::text('diaphragm', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Adauga detalii', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/technical_details/edit.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza detaliu tehnice</h1>

        <div class="row justify-content-center">
            {!! Form::model($details, ['method' => 'PATCH', 'action' => ['PhotoDetailsController@update', $details->id]]) !!}

            <div class="form-group">
                {!! Form::label('iso', 'ISO:') !!}
                {!! Form::text('iso', null, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza detaliu', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/technical_details/edit1.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza camera</h1>

        <div class="row justify-content-center">
            {!! Form::model($details1, ['method' => 'PUT', 'action' => ['PhotoDetailsController@update1', $details1->id]]) !!}

            <div class="form-group">
                {!! Form::label('camera', 'Camera') !!}
                {!! Form::text('camera', $details1->camera, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza detaliu', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>
    </div>
@endsection

resources/views/back_admin/technical_details/edit2.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza expunerea</h1>

        <div class="row justify-content-center">
            {!! Form::model($details2, ['method' => 'PUT', 'action' => ['PhotoDetailsController@update2', $details2->id]]) !!}

            <div class="form-group">
                {!! Form::label('exposure', 'Expunerea:') !!}
                {!! Form::text('exposure', $details2->exposure, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza detaliu', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/technical_details/edit3.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza obiectivul</h1>

        <div class="row justify-content-center">
            {!! Form::model($details3, ['method' => 'PUT', 'action' => ['PhotoDetailsController@update1', $details3->id]]) !!}

            <div class="form-group">
                {!! Form::label('lens', 'Obiectiv:') !!}
                {!! Form::text('lens', $details3->camera, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza detaliu', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/technical_details/edit4.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza diafragma</h1>

        <div class="row justify-content-center">
            {!! Form::model($details4, ['method' => 'PUT', 'action' => ['PhotoDetailsController@update4', $details4->id]]) !!}

            <div class="form-group">
                {!! Form::label('diaphragm', 'Diafragma:') !!}
                {!! Form::text('diaphragm', $details4->camera, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza detaliu', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/technical_details/index.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
<div class="container" id="details">
    <div class="row">
        <div class="col-8">
            <h1>Detaliile Tehnice ale unei fotografii</h1>
        </div>
        <div class="col-4" style="padding-left: 185px;padding-top: 10px;">
            <a class="btn btn-primary" href="{{route('details.create')}}">Adauga un detaliu</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>ISO</th>
                <th>Șterge</th>
                <th>Editează</th>
            </tr>
        </thead>
        <tbody>
            @if($details)
            @foreach($details as $detail)
            <tr>
                <td>{{$detail->id}}</td>
                <td>{{Str::limit($detail-> iso, $limit = 27, $end = '...')}}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'action' => ['PhotoDetailsController@destroy', $detail->id]]) !!}

                    {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                    {!! Form::close() !!}
                </td>
                <td><a class="btn btn-primary" href="{{route('details.edit', $detail->id)}}">Editează</a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

    <div class="col-12 justify-content-center d-flex mt-3 mb-3">
        {{ $details->links() }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Camera</th>
                <th>Șterge</th>
                <th>Editează</th>
            </tr>
        </thead>
        <tbody>
            @if($details1)
            @foreach($details1 as $detail)
            <tr>
                <td>{{$detail->id}}</td>
                <td>{{Str::limit($detail-> camera, $limit = 27, $end = '...')}}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'action' => ['PhotoDetailsController@destroy1', $detail->id]]) !!}

                    {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                    {!! Form::close() !!}
                </td>
                <td><a class="btn btn-primary" href="{{route('details.edit1', $detail->id)}}">Editează</a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

    <div class="col-12 justify-content-center d-flex mt-3 mb-3">
        {{ $details1->links() }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Exposure</th>
                <th>Șterge</th>
                <th>Editează</th>
            </tr>
        </thead>
        <tbody>
            @if($details2)
            @foreach($details2 as $detail)
            <tr>
                <td>{{$detail->id}}</td>
                <td>{{Str::limit($detail-> exposure, $limit = 27, $end = '...')}}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'action' => ['PhotoDetailsController@destroy2', $detail->id]]) !!}

                    {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                    {!! Form::close() !!}
                </td>
                <td><a class="btn btn-primary" href="{{route('details.edit2', $detail->id)}}">Editează</a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

    <div class="col-12 justify-content-center d-flex mt-3 mb-3">
        {{ $details2->links() }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Obiectiv</th>
                <th>Șterge</th>
                <th>Editează</th>
            </tr>
        </thead>
        <tbody>
            @if($details3)
            @foreach($details3 as $detail)
            <tr>
                <td>{{$detail->id}}</td>
                <td>{{Str::limit($detail-> lens, $limit = 27, $end = '...')}}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'action' => ['PhotoDetailsController@destroy3', $detail->id]]) !!}

                    {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                    {!! Form::close() !!}
                </td>
                <td><a class="btn btn-primary" href="{{route('details.edit3', $detail->id)}}">Editează</a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

    <div class="col-12 justify-content-center d-flex mt-3 mb-3">
        {{ $details3->links() }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Diafragma</th>
                <th>Șterge</th>
                <th>Editează</th>
            </tr>
        </thead>
        <tbody>
            @if($details4)
            @foreach($details4 as $detail)
            <tr>
                <td>{{$detail->id}}</td>
                <td>{{Str::limit($detail-> diaphragm, $limit = 27, $end = '...')}}</td>
                <td>
                    {!! Form::open(['method' => 'DELETE', 'action' => ['PhotoDetailsController@destroy4', $detail->id]]) !!}

                    {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                    {!! Form::close() !!}
                </td>
                <td><a class="btn btn-primary" href="{{route('details.edit4', $detail->id)}}">Editează</a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>

    <div class="col-12 justify-content-center d-flex mt-3 mb-3">
        {{ $details4->links() }}
    </div>

</div>
@endsection