routes/web.php
<?php

use App\Http\Middleware\IsAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin pages
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::resource('/admin/details', 'PhotoDetailsController')->middleware('is_admin');
Route::resource('/admin/announcements', 'AnnouncementsController')->middleware('is_admin');
Route::resource('/admin/challenges', 'WeeklyChallengeController')->middleware('is_admin');
Route::resource('/admin/gallery', 'GalleryController')->middleware('is_admin');
Route::resource('/admin/blog', 'BlogController')->middleware('is_admin');
Route::resource('/admin/sales', 'SalesController')->middleware('is_admin');
Route::resource('/admin/workshop', 'WorkshopController')->middleware('is_admin');
Route::resource('/admin/courses', 'CoursesController')->middleware('is_admin');


//Route::resource('admin/blog', 'BlogController');

//user pages
Route::get('/home' , [
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::get('/test', function () {
   return view('admin');
});

//site
Route::get('/', function () {
    return redirect()->route('intro');
})->name('index');

Route::get('/intro', function () {
    return view('Front.includes.intro');
})->name('intro');

Route::post('contact-us', [
    'uses'=>'WebController@contactUs',
    'as'=>'contact-us']
);

Route::get('/blog', [
    'uses' => 'WebController@paginateBlog',
    'as' => 'blog'
]);
Route::resource('blogArticle', 'BlogController');

Route::get('/sales', [
    'uses' => 'WebController@paginateSales',
    'as' => 'sales'
]);

Route::get('/workshop', [
    'uses' => 'WebController@paginateWorkshos',
    'as' => 'workshop'
]);

Route::get('/increaseWorkshop', [
    'uses' => 'WebController@increaseWorkshopParticipate',
    'as' => 'increaseWorkshop'
]);

Route::get('/courses', function () {
    return view('Front.includes.courses');
})->name('courses');

Route::get('/gallery', 'WebController@getAllImages')->name('gallery');

Route::get('/weekly', [
    'uses' => 'WebController@getCurentWeeklyChallenge',
    'as' => 'weekly'
]);

Route::get('/increaseLike', [
    'uses' => 'WebController@increaseLike',
    'as' => 'increaseLike'
]);

Route::get('/increaseView', [
    'uses' => 'WebController@increaseView',
    'as' => 'increaseView'
]);

Route::get('/increaseVoteChallenge', [
    'uses' => 'WebController@increaseVoteChallenge',
    'as' => 'increaseVoteChallenge'
]);

Route::post('/uploadWeekly', [
    'uses' => 'WebController@uploadWeekly',
    'as' => 'uploadWeekly'
]);

Route::get('/blog/searchBlog/{variable}',[
   'uses' => 'WebController@searchBlog',
   'as' => 'searchBlog'
]);



//admin-panel
Route::get('/admin/camera/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit1',
    'as' => 'details.edit1'
]);
Route::put('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@update1',
    'as' => 'details.update1'
]);
Route::delete('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@destroy1',
    'as' => 'details.destroy1'
]);


Route::get('/admin/exposure/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit2',
    'as' => 'details.edit2'
]);
Route::put('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@update2',
    'as' => 'details.update2'
]);
Route::delete('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@destroy2',
    'as' => 'details.destroy2'
]);

Route::get('/admin/lens/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit3',
    'as' => 'details.edit3'
]);
Route::put('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@update3',
    'as' => 'details.update3'
]);
Route::delete('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@destroy3',
    'as' => 'details.destroy3'
]);

Route::get('/admin/diaphragm/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit4',
    'as' => 'details.edit4'
]);
Route::put('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@update4',
    'as' => 'details.update4'
]);
Route::delete('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@destroy4',
    'as' => 'details.destroy4'
]);

Route::delete('/admin/photos/{details}', [
    'uses' => 'WeeklyChallengeController@destroyPhoto',
    'as' => 'weekly.destroyPhoto'
]);


Auth::routes();

resources/views/back_admin/includes/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/back_admin/includes/navigation.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Topbar Search -->
    {{-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> --}}

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <!-- Authentication Links -->
        @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Autentificare') }}</a>
            </li>
            {{--                    @if (Route::has('register'))--}}
            {{--                        <li class="nav-item">--}}
            {{--                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
            {{--                        </li>--}}
            {{--                    @endif--}}
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                    {{ Auth::user()->name }} 
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Deconectare') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
    </ul>

</nav>
<!-- End of Topbar -->


{{--<nav class="navbar navbar-expand-md navbar-light">--}}
{{--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"--}}
{{--            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">--}}
{{--        <span class="navbar-toggler-icon"></span>--}}
{{--    </button>--}}

{{--    <div class="collapse navbar-collapse" id="navbarSupportedContent">--}}
{{--        <!-- Left Side Of Navbar -->--}}
{{--        <ul class="navbar-nav mr-auto">--}}

{{--        </ul>--}}

{{--        <!-- Right Side Of Navbar -->--}}
{{--        <ul class="navbar-nav ml-auto">--}}
{{--            <!-- Authentication Links -->--}}
{{--            @guest--}}
{{--                <li class="nav-item">--}}
{{--                    <a class="nav-link" href="{{ route('login') }}">{{ __('Autentificare') }}</a>--}}
{{--                </li>--}}
{{--                --}}{{--                    @if (Route::has('register'))--}}
{{--                --}}{{--                        <li class="nav-item">--}}
{{--                --}}{{--                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                --}}{{--                        </li>--}}
{{--                --}}{{--                    @endif--}}
{{--            @else--}}
{{--                <li class="nav-item dropdown">--}}
{{--                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"--}}
{{--                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>--}}
{{--                        {{ Auth::user()->name }} <span class="caret"></span>--}}
{{--                    </a>--}}

{{--                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">--}}
{{--                        <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--                           onclick="event.preventDefault();--}}
{{--                                                     document.getElementById('logout-form').submit();">--}}
{{--                            {{ __('Deconectare') }}--}}
{{--                        </a>--}}

{{--                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--                            @csrf--}}
{{--                        </form>--}}
{{--                    </div>--}}
{{--                </li>--}}
{{--            @endguest--}}
{{--        </ul>--}}
{{--    </div>--}}
{{--</nav>--}}

resources/views/back_admin/includes/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion text-center" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Panou Administrativ</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{route('admin.home')}}" aria-expanded="false">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    {{-- <div class="sidebar-heading">
        Interface
    </div> --}}

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('gallery.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-cog"></i>
            <span>Galerie Foto</span>
        </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('details.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Detalii tehnice</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('blog.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Articole</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('courses.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Cursuri online</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('workshop.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Workshops</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('challenges.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Weekly Challenge</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('announcements.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Anunțuri Online</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="{{route('sales.index')}}" aria-expanded="false">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Vanzări produse / </span>
            <span>Licitații</span>
        </a>
    </li>

    {{-- <li class="nav-item">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilizatori</span>
        </a>
    </li> --}}

    <!-- Divider -->
    <hr class="sidebar-divider">
</ul>
<!-- End of Sidebar -->

resources/views/back_admin/includes/success_message.blade.php
@if($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif