routes/web.php
<?php

use App\Http\Middleware\IsAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin pages
Route::get('admin/home', 'HomeController@adminHome')->name('admin.home')->middleware('is_admin');

Route::resource('/admin/details', 'PhotoDetailsController')->middleware('is_admin');
Route::resource('/admin/announcements', 'AnnouncementsController')->middleware('is_admin');
Route::resource('/admin/challenges', 'WeeklyChallengeController')->middleware('is_admin');
Route::resource('/admin/gallery', 'GalleryController')->middleware('is_admin');
Route::resource('/admin/blog', 'BlogController')->middleware('is_admin');
Route::resource('/admin/sales', 'SalesController')->middleware('is_admin');
Route::resource('/admin/workshop', 'WorkshopController')->middleware('is_admin');
Route::resource('/admin/courses', 'CoursesController')->middleware('is_admin');


//Route::resource('admin/blog', 'BlogController');

//user pages
Route::get('/home' , [
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Route::get('/test', function () {
   return view('admin');
});

//site
Route::get('/', function () {
    return redirect()->route('intro');
})->name('index');

Route::get('/intro', function () {
    return view('Front.includes.intro');
})->name('intro');

Route::post('contact-us', [
    'uses'=>'WebController@contactUs',
    'as'=>'contact-us']
);

Route::get('/blog', [
    'uses' => 'WebController@paginateBlog',
    'as' => 'blog'
]);
Route::resource('blogArticle', 'BlogController');

Route::get('/sales', [
    'uses' => 'WebController@paginateSales',
    'as' => 'sales'
]);

Route::get('/workshop', [
    'uses' => 'WebController@paginateWorkshos',
    'as' => 'workshop'
]);

Route::get('/increaseWorkshop', [
    'uses' => 'WebController@increaseWorkshopParticipate',
    'as' => 'increaseWorkshop'
]);

Route::get('/courses', function () {
    return view('Front.includes.courses');
})->name('courses');

Route::get('/gallery', 'WebController@getAllImages')->name('gallery');

Route::get('/weekly', [
    'uses' => 'WebController@getCurentWeeklyChallenge',
    'as' => 'weekly'
]);

Route::get('/increaseLike', [
    'uses' => 'WebController@increaseLike',
    'as' => 'increaseLike'
]);

Route::get('/increaseView', [
    'uses' => 'WebController@increaseView',
    'as' => 'increaseView'
]);

Route::get('/increaseVoteChallenge', [
    'uses' => 'WebController@increaseVoteChallenge',
    'as' => 'increaseVoteChallenge'
]);

Route::post('/uploadWeekly', [
    'uses' => 'WebController@uploadWeekly',
    'as' => 'uploadWeekly'
]);

Route::get('/blog/searchBlog/{variable}',[
   'uses' => 'WebController@searchBlog',
   'as' => 'searchBlog'
]);



//admin-panel
Route::get('/admin/camera/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit1',
    'as' => 'details.edit1'
]);
Route::put('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@update1',
    'as' => 'details.update1'
]);
Route::delete('/admin/camera/{details}', [
    'uses' => 'PhotoDetailsController@destroy1',
    'as' => 'details.destroy1'
]);


Route::get('/admin/exposure/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit2',
    'as' => 'details.edit2'
]);
Route::put('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@update2',
    'as' => 'details.update2'
]);
Route::delete('/admin/exposure/{details}', [
    'uses' => 'PhotoDetailsController@destroy2',
    'as' => 'details.destroy2'
]);

Route::get('/admin/lens/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit3',
    'as' => 'details.edit3'
]);
Route::put('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@update3',
    'as' => 'details.update3'
]);
Route::delete('/admin/lens/{details}', [
    'uses' => 'PhotoDetailsController@destroy3',
    'as' => 'details.destroy3'
]);

Route::get('/admin/diaphragm/{details}/edit', [
    'uses' => 'PhotoDetailsController@edit4',
    'as' => 'details.edit4'
]);
Route::put('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@update4',
    'as' => 'details.update4'
]);
Route::delete('/admin/diaphragm/{details}', [
    'uses' => 'PhotoDetailsController@destroy4',
    'as' => 'details.destroy4'
]);

Route::delete('/admin/photos/{details}', [
    'uses' => 'WeeklyChallengeController@destroyPhoto',
    'as' => 'weekly.destroyPhoto'
]);


Auth::routes();

resources/views/back_admin/challenges/create.blade.php
@extends('back_admin.layouts.back_layouts')
@section('content')
    <div class="container">
        <h1 style="text-align: center">Adaugă un concurs săptămânal</h1>

        <div class="row justify-content-center">
            <form action="{{route('challenges.store')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    {!! Form::label('title', 'Titlu:') !!}
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-group">
                    <label for="image">Imagine concurs</label>
                    <input type="file" name="image" class="form-control">
                </div>

                <div class="form-group">
                    {!! Form::label('description', 'Descriere:') !!}
                    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">Adaugă concurs</button>
                </div>
            </form>
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/challenges/edit.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
    <div class="container">
        <h1 style="text-align: center">Editeaza un articol</h1>

        <div class="row justify-content-center">
            {!! Form::model($weekly, ['method' => 'PATCH', 'action' => ['BlogController@update', $weekly->id], 'enctype' => 'multipart/form-data']) !!}

            <div class="form-group">
                {!! Form::label('title', 'Titlu:') !!}
                {!! Form::text('title', $weekly->title, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('description', 'Descriere') !!}
                {!! Form::textarea('description', $weekly->description, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('category', 'Categorii:') !!}
                {!! Form::text('category', $weekly->category, ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('blog_image', 'Fotografie:') !!}
                <img src="{{asset('images/backImages/blog/' . $weekly->image)}}" alt="">
                {!! Form::file('blog_image', ['class' => 'form-control']) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Actualizeaza un challenge', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>

        <div class="row">
            @include('back_admin.includes.errors')
        </div>

    </div>
@endsection

resources/views/back_admin/challenges/index.blade.php
@extends('back_admin.layouts.back_layouts')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-8">
            <h1>Concurs - Weekly Challenge</h1>
        </div>
        <div class="col-4" style="padding-left: 185px;padding-top: 10px;">
            <a class="btn btn-primary" href="{{route('challenges.create')}}">Adauga un challenge</a>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Titlu</th>
                    <th>Descriere</th>
                    <th>Imagine</th>
                    <th>Șterge</th>
                    <th>Editează</th>
                </tr>
            </thead>
            <tbody>
                @if($weekly)
                @foreach($weekly as $item)
                <tr>
                    <td>{{$item->id}}</td>
                    <td>{{$item->title}}</td>
                    <td>{{$item->description}}</td>
                    <td><img src="{{asset('images/backImages/weekly/' . $item->image)}}" width="150px" alt=""></td>
                    <td>
                        {!! Form::open(['method' => 'DELETE', 'action' => ['WeeklyChallengeController@destroy', $item->id]]) !!}

                        {!! Form::submit('Șterge', ['class' => 'btn btn-danger close-icon']) !!}

                        {!! Form::close() !!}
                    </td>
                    <td><a class="btn btn-primary" href="{{route('challenges.edit', $item->id)}}">Editează</a></td>
                </tr>
                @endforeach
                @endif
            </tbody>
        </table>
        <div class="col-12 justify-content-center d-flex mt-3 mb-3">
            {{ $weekly->links() }}
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-8">
            <h1>Concurs - Fotografii Weekly Challenge</h1>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th>Titlu</th>
                    <th>Descriere</th>
                    <th>Imagine</th>
                    <th>Voturi</th>
                </tr>
            </thead>
            <tbody>
                @if($photos)
                @foreach($photos as $item)
                <tr>
                    <td>{{$item->title}}</td>
                    <td>{{$item->description}}</td>
                    <td><img src="{{asset('images/backImages/weeklyPhoto/' . $item->image)}}" width="150px" alt=""></td>
                    <td>{{$item->votes}}</td>
                    <td>
                        {!! Form::open(['method' => 'DELETE', 'action' => ['WeeklyChallengeController@destroyPhoto', $item->id]]) !!}

                        {!! Form::submit('Descalifica', ['class' => 'btn btn-danger close-icon']) !!}

                        {!! Form::close() !!}
                    </td>
                </tr>
                @endforeach
                @endif
            </tbody>
        </table>
        <div class="col-12 justify-content-center d-flex mt-3">
            {{ $photos->links() }}
        </div>
    </div>
</div>
@endsection